[package]
name = "rpc_proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.11.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
dotenv = "0.15.0"
tokio = "1.28.0"
